### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by osintgithub** [novitae/Tenai#5]
Ran this program for the first time a few days ago and it worked perfectly. Getting errors now.

```
Traceback (most recent call last):
  File "/usr/local/bin/tenai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tenai/core.py", line 126, in main
    output = filter(result)
  File "/usr/local/lib/python3.9/site-packages/tenai/core.py", line 92, in filter
    return [user for user in Dict["users"] if "11" in user["chaining_info"]["sources"]]
  File "/usr/local/lib/python3.9/site-packages/tenai/core.py", line 92, in <listcomp>
    return [user for user in Dict["users"] if "11" in user["chaining_info"]["sources"]]
TypeError: argument of type 'NoneType' is not iterable
```

Maybe IG has changed the API?

**Comment by novitae** [comment]
> Maybe IG has changed the API?

Yup it seems they did, I'm gonna investigate further to see on private iOS API. Otherwise, rip tenais :(
